#!/usr/bin/env bash
set -euxo pipefail

IBCPAF_DOWNLOAD_DIR=/ibcpaf_download_dir
IB_CLIENT_PORTAL_URL="https://download2.interactivebrokers.com/portal/clientportal.gw.zip"

# Currently there's no "version" so we use the last modified date of the file to know what the "version" is.
last_modified=$(curl -Is $IB_CLIENT_PORTAL_URL | grep -Po 'Last-Modified: \K.+')
last_modified_ymd=$(date -d "${last_modified}" '+%Y-%m-%d')
target_file="${IBCPAF_DOWNLOAD_DIR}/${last_modified_ymd}.clientportal.gw.zip"

if [[ ! -f ${target_file} ]]; then
  curl --dump-header /dev/fd/1 --no-progress-meter -m120 ${IB_CLIENT_PORTAL_URL} -o ${target_file}
fi

# Only keep the latest 3 versions (by modification time)
ls -tQ /ibcpaf_download_dir | tail -n+4 | xargs --no-run-if-empty rm
