name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Push to Docker Hub version latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: daazku/interactivebroker-client-portal-api-fetcher:latest
      - name: Push to Docker Hub version ${{ steps.get_version.outputs.VERSION }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: daazku/interactivebroker-client-portal-api-fetcher:${{ steps.get_version.outputs.VERSION }}
